name: aqueduct_app
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.1.0
  rxdart: ^0.20.0

  sqljocky5: ^2.2.0
  jaguar_orm: ^2.2.5
  jaguar_query_sqljocky: ^2.2.4

  json_serializable: ^2.0.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0